# Generated by Django 5.1.4 on 2024-12-29 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_profile.gameprofile')),
            ],
        ),
    ]
