# Generated by Django 5.1.4 on 2024-12-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game', '0002_alter_livegame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livegame',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
