# Generated by Django 5.1.4 on 2024-12-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game', '0003_alter_livegame_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livegame',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
    ]
