# Generated by Django 5.1.4 on 2024-12-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game', '0006_livegame_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='livegame',
            name='bet_amount',
            field=models.DecimalField(decimal_places=2, default=10, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
