# Generated by Django 5.1.4 on 2024-12-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game', '0007_livegame_bet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livegame',
            name='bet_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
