# Generated by Django 5.1.4 on 2025-04-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game', '0009_alter_livegame_bet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='livegame',
            name='is_manually_set',
            field=models.BooleanField(default=False),
        ),
    ]
