# Generated by Django 5.1.4 on 2025-01-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='loss_return',
        ),
    ]
