# Generated by Django 5.1.4 on 2024-12-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WithdrawalRequest',
            new_name='Payment',
        ),
    ]
