# Generated by Django 5.1.4 on 2025-03-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_setting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesetting',
            name='updated_by',
        ),
    ]
