# Generated by Django 5.1.4 on 2024-12-29 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('live_game', '0003_alter_livegame_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue')], max_length=4)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_game.livegame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
