# Generated by Django 5.1.4 on 2024-12-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_game', '0002_alter_usergame_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
