# Generated by Django 5.1.4 on 2024-12-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_game', '0003_usergame_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergame',
            name='status',
        ),
    ]
