# Generated by Django 5.1.4 on 2024-12-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_game', '0004_remove_usergame_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergame',
            old_name='live_game',
            new_name='game',
        ),
    ]
