# Generated by Django 5.1.4 on 2024-12-29 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('user_game', '0005_rename_live_game_usergame_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
