# Generated by Django 5.1.4 on 2024-12-30 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_game', '0006_alter_usergame_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
