# Generated by Django 5.1.4 on 2024-12-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_game', '0008_remove_usergame_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergame',
            name='bet_amount',
        ),
    ]
